<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StatisticsService.API</RootNamespace>
    <UserSecretsId>570501ff-860f-4042-a15f-206782f968fd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StatisticsService.Services\StatisticsService.Services.csproj" />
    <ProjectReference Include="..\StatisticsService.Infrastructure\StatisticsService.Infrastructure.csproj" />
    <ProjectReference Include="..\StatisticsService.DTO\StatisticsService.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <!-- IDistributedCache cu backend Redis -->
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.0" />
  </ItemGroup>

</Project>
