<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StatisticsService.DTO</RootNamespace>
  </PropertyGroup>

  <!-- Niciun NuGet — doar record-uri simple fara dependente -->

</Project>
